### ISSUE TITLE
Negative path not working

### ISSUE THREAD

**Issue by SilviaElisaAimone** [lgndhq/path-draggable-button#1]
Hi! The negative parameter is not working. I downloaded your demo and tried to change the negative param in the third .toggle-switch-container. It doesn't work. Do I need to change something else? thanks!

**Comment by mccahan** [comment]
Hello! Looks like I hadn't correctly implemented the negative parameter for vertical sliders - I went ahead and added support in 2df5b295d681e66afada2e90f651626f697d43a6 and updated the demo if you'd like to grab it again and re-try.

Let me know if that doesn't solve the problem for you!

**Comment by mccahan** [comment]
One small usability note that might not be super clear in my docs, make sure that if you're setting the negative parameter to true that your SVG path also goes from bottom to top. You can see in the updated demo file that I also reversed the direction of the path to match when I set `negative` to true.
